version: '3.8'
services:
  app:
    build: 
      context: ..
      dockerfile: ./dockerfile
    ports:
      - '3001:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nest
    depends_on:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "run", "start:prod"]

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=30  # Check for updates every 30 seconds
volumes:
  mongo-data: