version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: ./dockerfile
    ports:
      - '3001:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nest
    depends_on:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "run", "start:prod"]

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: